# All used classes are defined and have a label
PREFIX rdf:     <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs:    <http://www.w3.org/2000/01/rdf-schema#>
PREFIX owl:     <http://www.w3.org/2002/07/owl#>

SELECT DISTINCT * {
  {
    [] a ?c .
    FILTER NOT EXISTS { { ?c a owl:Class } UNION { ?c a rdfs:Class } } .
  } UNION {
    [] a ?c .
    FILTER NOT EXISTS { ?c rdfs:label ?l } .
  }
}
