# Any referenced parent codes must exist
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
SELECT * WHERE {
  ?codelist skos:member ?code .
  ?code skos:broader ?parent_code .
  
  FILTER NOT EXISTS {
    ?parent_code ?p ?o
  }
} LIMIT 1000
